name: Terraform CI (Docker)

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Init & Validate (Docker)
    runs-on: ubuntu-latest

    container:
      image: hashicorp/terraform:1.13.3   # Use Terraform 1.13.3

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 3: Terraform Validate
      - name: Terraform Validate
        run: terraform validate
